# Enable the Extent Spark Report
extent.reporter.spark.start=true
extent.reporter.spark.out=test-output/SparkReport/Spark.html
# Configuration settings
systeminfo.os=Windows 11
systeminfo.project=Selenium Automation Framework
extent.reporter.spark.config=src/test/resources/extent-config.xml
# Force screenshots to be embedded directly as base64 data inside the HTML file
extent.reporter.spark.base64imagesrc=true